version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_REGISTRY_URL:-localhost}/ecommerce-app:${CI_COMMIT_SHA:-latest}
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == node-1
      restart_policy:
        condition: on-failure
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb+srv://dik:diko@cluster0.7tkxp.mongodb.net/web_logs?retryWrites=true&w=majority}
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: overlay