name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        CI_COMMIT_SHA: ${{ github.sha }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        docker-compose build
        docker-compose push

    - name: Deploy to Docker Swarm
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        CI_COMMIT_SHA: ${{ github.sha }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: |
        docker stack deploy --compose-file docker-compose.yml --with-registry-auth ecommerce-stack