name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Для отладки: пропустим этап логина в Docker Hub
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build Docker image locally (no push)
      run: |
        docker build -t ecommerce-app:latest .
        echo "Image built successfully: ecommerce-app:latest"
    
    - name: Deploy to Docker Swarm
      run: |
        echo "Deploying to Docker Swarm..."
        
        # Создаем временный docker-compose.yml файл
        cat > deploy-compose.yml << EOL
        version: '3.8'
        
        services:
          ecommerce-app:
            image: ecommerce-app:latest
            ports:
              - "5000:5000"
            deploy:
              replicas: 2
              placement:
                constraints:
                  - node.role == worker
              restart_policy:
                condition: on-failure
              update_config:
                parallelism: 1
                delay: 10s
                order: start-first
            networks:
              - ecommerce-network
        
        networks:
          ecommerce-network:
            driver: overlay
        EOL
        
        # Вывод для отладки
        echo "Deploying stack with the following configuration:"
        cat deploy-compose.yml
        
        # Развертывание в Docker Swarm
        docker stack deploy --compose-file deploy-compose.yml ecommerce-stack
        
        # Проверка статуса развертывания
        echo "Stack services status:"
        docker stack services ecommerce-stack
